add_lunch_combo du_m7att-userdebug
add_lunch_combo du_m7spr-userdebug
add_lunch_combo du_m7tmo-userdebug
add_lunch_combo du_m7ul-userdebug
add_lunch_combo du_mako-userdebug
add_lunch_combo du_hercules-userdebug
add_lunch_combo du_l900-userdebug
add_lunch_combo du_exhilarate-userdebug
add_lunch_combo du_t769-userdebug
add_lunch_combo du_d2cri-userdebug

