add_lunch_combo du_m7tmo-userdebug
add_lunch_combo du_m7ul-userdebug
dd_lunch_combo du_m7att-userdebug
add_lunch_combo du_m7spr-userdebug
add_lunch_combo du_mako-userdebug
add_lunch_combo du_hercules-userdebug

